### ISSUE TITLE
Cannot build the source code

### ISSUE THREAD

**Issue by cloudhuang** [aliyun/aliyun-maxcompute-data-collectors#10]
Here, I'm trying to build the package from source codes, but get the error when execute the maven build

> [ERROR] Failed to execute goal on project aliyun-odps-kettle-plugin: Could not resolve dependencies for project com.aliyun.odps:aliyun-odps-kettle-plugin:jar:2.0.2: Could not find artifact com.aliyun:maxcompute.data.collectors.common:jar:2.0.2 in pentaho-releases (http://repository.pentaho.org/artifactory/repo/) -> [Help 1]

**Comment by cloudhuang** [comment]
Sorry, need to build the whole project from parent path at the first time.

**Comment by zhangyiw** [comment]
I build the whole project but failed in aliyun-odps-kettle-plugin
