### ISSUE TITLE
构建aliyun-odps-kettle-plugin组件失败

### ISSUE THREAD

**Issue by zhangyiw** [aliyun/aliyun-maxcompute-data-collectors#20]
Reactor Summary:
[INFO]
[INFO] Open Data Processing Service ....................... SUCCESS [  1.821 s]
[INFO] maxcompute.data.collectors.common .................. SUCCESS [ 13.113 s]
[INFO] odps-flume-plugin .................................. SUCCESS [ 18.087 s]
[INFO] aliyun-odps-kettle-plugin .......................... FAILURE [  0.717 s]
[INFO] aliyun-datahub-ogg-plugin .......................... SKIPPED
[INFO] odps-sqoop ......................................... SKIPPED
[INFO] odps_data_dumper ................................... SKIPPED

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error reading /java/mvn/apache-maven-3.2.5/repo/swt/swt-win32/3.0m8/swt-win32-3.0m8.jar; error in opening zip file
[ERROR] error reading /java/mvn/apache-maven-3.2.5/repo/swt/swt-win32/3.0m8/swt-win32-3.0m8.jar; error in opening zip file

**Comment by cornmonster** [comment]
如果不需要kettle-plugin的话可以删掉这个目录，并把root pom中的这个module删除。之后就可以正常build了。

**Comment by lyman** [comment]
看起来是从 repo 下载下来的 jar 包是坏的，可以删了试试看

**Comment by zhangyiw** [comment]
是我用maven下载的jar有问题？
