### ISSUE TITLE
Adding configuration for <tunnel_endpoint>xxx</tunnel_endpoint> 

### ISSUE THREAD

**Issue by krgv** [aliyun/aliyun-maxcompute-data-collectors#4]
Objective: To be able to configure tunnel_endpoint on the pdi plugin. 
Issue: Our current connection to service.ap-southeast-1.maxcompute.aliyun.com does not work unless we specify the tunnel endpoint as well but there is no such configuration available on the pdi plugin.
Please help. Thanks in advance :)

**Comment by oyz** [comment]
https://github.com/aliyun/aliyun-maxcompute-data-collectors/commit/d765f41cd86aab9cca39d2067ee79db40525dd2b

the added configuration name is tunnelEndpoint.
