### ISSUE TITLE
MaxCompute Kettle插件支持二级分区

### ISSUE THREAD

**Issue by chumucainiao** [aliyun/aliyun-maxcompute-data-collectors#8]
目前只支持一级分区
![image](https://user-images.githubusercontent.com/29447307/29510241-ad9818e0-868d-11e7-8ba4-c852512a9f2b.png)

**Comment by oyz** [comment]
从目前的实现看，多级分区也是支持，多级分区写法如ds=20170821,hh=15   多个之间用逗号分隔
